### ISSUE TITLE
How to get 'Out of office' user status

### ISSUE THREAD

**Issue by bmalets** [ebeigarts/exchanger#14]
Hi Ebeigarts,

At first, Kindly thank you for such great gem :)
I have a small question about opportunity to get 'Out of office' user status from exchange,
I found in MSDN documentation this API: http://msdn.microsoft.com/en-us/library/aa493825.aspx

I think it should be a cool possibility to check is user in office and free to communication or are absent today. 

So, have your gem opportunity to get 'Out of office' user status? 
Thanks a lot

**Comment by ebeigarts** [comment]
Sorry for the long delay, currently exchanger doesn't support out of office requests. Pull requests are welcome.
