### ISSUE TITLE
Add to rails application

### ISSUE THREAD

**Issue by Herz3h** [ebeigarts/exchanger#20]
Hello,

This is probably a stupid question but i can't include the library in my rails application.

I added this to my Gemfile

`gem 'exchanger'
`
and after running bundle, it got installed properly.

But when i try to do this : 

```
folder = Exchanger::Folder.find(:calendar)
folder.items # return Exchanger::CalendarItem items
```

It tells me : uninitialized constant Exchanger

I added a require 'exchanger' in the controller where i put the code above. So i don't know what to do.

Please help, thanks!

**Comment by ebeigarts** [comment]
@Herz3h it should work, can you check what happens in rails console when you do

```
require 'exchanger'
Exchanger
```

**Comment by ebeigarts** [comment]
It should output something like:

```
$ gem install exchanger
Fetching: exchanger-0.2.0.gem (100%)
Successfully installed exchanger-0.2.0
$ irb
>> require "exchanger"
true
>> Exchanger
Exchanger
```

**Comment by ebeigarts** [comment]
If you can't figure it out, can you show me your Gemfile and Gemfile.lock files?

**Comment by Herz3h** [comment]
It works in the IRB console after doing a manual : 

`gem install exchanger`

But not in the rails application, and here's my Gemfile : http://termbin.com/zy9x

**Comment by Herz3h** [comment]
Ok it works, had to restart the server...Sorry and thanks for the help !
